version: '2'
services:
  ppc32-fmt-pwn:
    build: challenges/ppc32-simple-fmt
    volumes:
      - shared-data:/shared
    ports:
      - "9001:9000"
    environment:
      - CHALLENGE_NAME=lvl1-uhoh
      - PWNFLAG=FLAG_GOES_HERE
    restart: always
  x86-64-sandboxie:
    build: challenges/x86-64-sandbox
    volumes:
      - shared-data:/shared
    ports:
      - "9002:9000"
    environment:
      - CHALLENGE_NAME=lvl2-box
      - PWNFLAG=FLAG_GOES_HERE
    restart: always
  x86-64-sandboxie:
    build: challenges/dotnet-deserialization
    volumes:
      - shared-data:/shared
    ports:
      - "9003:9000"
    environment:
      - CHALLENGE_NAME=lvl3-net
      - PWNFLAG=FLAG_GOES_HERE
    restart: always




volumes:
  shared-data:
